### PR TITLE
Moving search plugin selection to bottom-sheet

### PR DESCRIPTION
**Pull request by bbogdanov**
Moving the search plugin selection to use bottom-sheet. The layout using the selection component is really unstable and hard to use especially on mobile.

Also updated the comparison operators and some missing comas.

### CODE REVIEW

**Comment by CzBiX** [comment]
Bottom sheet is not easy to use on desktop. 😕
How about drop support for multi search engine selection.

**Comment by bbogdanov** [comment]
The plugin feature is one of the main features of the search so I think dropping the multi-search engine selection is something most of the users are going to miss. I agree the bottom sheet on the desktop is not the best approach.

What about getting this in and I'll think of something to bring better experience on the desktop next week?

**Comment by bbogdanov** [comment]
If you have any suggestions, let's discuss it.

**Comment by CzBiX** [comment]
In my mind, the most used options will be `all` and `one`, and it defaults to `all`.
It feels rare to choose some search engines every time you try to search.
However, I personally don't use this feature much, and I choose `one` when I use it.
So I listen to you. Let me know if it's ok to merge.

Just checked `Github discussions`, it need apply and at least 3 collaborators. 🤣

**Comment by bbogdanov** [comment]
After stepping back from the scenario for two days I think the next step is to provide a way to enable/disable plugins. That way you won't select plugins all the time because you will enable these that you know fit you best. I also think choosing only one to use it is a rare situation so I think having a modal to choose the one you would like to use in the current moment is the best solution for desktop. What do you think?

About GitHub discussions.... I have no words :D What you think about setting up a slack channel or Gitter?

**Pull request merged**
