### PR TITLE
add/update some sites

### PR DESCRIPTION
**Pull request by IITII**
1. merge site from #136 
2. add kamept, nicept, 2xfree
3. update site name
4. update site icons

* Some sites such as btschool, hddolby, haidai have no icon because of download failure(403, 404, 502).

> Add site icon download script with .eslintignore

### CODE REVIEW

**Comment by IITII** [comment]
I've found something nice too. Looks a bit like grouping by storage path. Possibly merged in?

https://github.com/hxsf/qb-web/tree/feature/group-by-savepath

**Comment by IITII** [comment]
I also think add i18n support for tracker name is good, but I don't know how to do....

**Comment by IITII** [comment]
[qbweb.zip](https://github.com/CzBiX/qb-web/files/11213461/qbweb.zip)

**Comment by CzBiX** [comment]
感觉没必要给tracker name加翻译功能，直接使用站点自己的名称就好。

**Comment by IITII** [comment]
主要是看着之前的commit说补充了English 翻译。
目前来说的话，从受众角度考虑，用ptpp的名称应该就够了。

CzBiX ***@***.***> 于 2023年4月13日周四 14:05写道：

**Comment by IITII** [comment]
@CzBiX 这个 PR 只涉及 站点的添加和图片的更新, 后面的都是建议, 想法. 
就这个 PR 而言请尽快 review, merge.

**Pull request merged**
